name: Deploy to dev

on:
  push:
    branches: [develop]
  workflow_dispatch:

concurrency:
  group: deploy-develop
  cancel-in-progress: true

jobs:
  deploy:
    uses: ./.github/workflows/_deploy.yml
    with:
      image_tag: latest
      env_slug: dev
      node_env: dev
    secrets: inherit
