name: Deploy to production

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: deploy-production
  cancel-in-progress: true

jobs:
  deploy:
    uses: ./.github/workflows/_deploy.yml
    with:
      image_tag: stable
      env_slug: prod
      node_env: prod
    secrets: inherit
