name: ReminderBot Prod
on:
  push:
    branches:
      - main
jobs:
  build:
    name: ReminderBotProd
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pnpm i

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to AWS server
        run: |
          ssh -i ${{ secrets.AWS_SSH_KEY }} ec2-16-16-217-110.eu-north-1.compute.amazonaws.com "cd ReminderBot && git pull origin main"
